### PR TITLE
Update Change Role Flow

### LINKED ISSUE #75: Change upgrade/downgrade admin flow

### PR DESCRIPTION
**Pull request by rexong**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Summary of PR
Fix #75 
## Details
Now there are 3 roles, User, Admin and Super Admin. 

1) User 
   - only can view questions
2) Admin
   - Can add/delete questions
3) Super Admin
   - Can upgrade/downgrade user role
   - Cannot add/delete questions

Super Admin can be upgrade if the user provides a key.
Currently, the key is just an env variable. 

## [Optional] Screenshots, Recordings

https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g13/assets/66376253/6fe5e106-73a4-4280-b29d-bd557c5e7e09

### CODE REVIEW

**Comment by ThomasHoooo** [comment]
Just thought of some edge cases, if admin user logged in -> super admin downgrades an admin -> then can admin still edit the questions?

**Comment by JovonLim** [comment]
At the end of the vid, it seems like the delete button remains unlike the add questions

**Comment by rexong** [comment]
For the edge case, the backend will catch that the user is not authorized and wont allow the questions to be added or deleted.

https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g13/assets/66376253/a5dc8710-87d7-4e8e-ad39-c359d79e9ed9

For the delete button, now it should be fixed, reflected in the video above as well

**Comment by ThomasHoooo** [comment]
Looks good

**Pull request merged**
